#!/bin/bash

 #########################################################################################################################
#   Author: Matt Blackmon AKA: Saloaty                                                                                    #
#                                                                                                                         #
#   Definition: Compile a list of IP addresses with port 22 open.                                                         #
#               Can also be configured for any other port                                                                 #
#                                                                                                                         #
#   Anyone may edit this script as needed. You may need to do some editing for it to work with your system at the moment  #
#   I will eventually make it so that it will prompt a few questions at the beginning so that it works for most everyone  #
#                                                                                                                         #
 #########################################################################################################################


IPDIR=/me/scanner # Directory of script
NUM=100 # How many hosts Nmap randomizes with each thread (4 threads iterated 10 (depending on the ITR variable) times)
PERC=0
RED='\033[0;31m' # Colorize output
PURPLE='\033[0;35m' # Colorize output
NC='\033[0m' # No color
ITR=$((NUM / 10)) # Change amount of while loop iterations / Also need to change PERC(10) if you're wanting a smaller percentage output 
ADDITR=$ITR # Add to the while loop iterator; Can probably be done a better way.
FILE=meta.txt # File for saving list of hosts
START=`wc -l $FILE | grep -o -E '[0-9]{1,4}'` # Variable was delcared to be able to show how many new IP's were added at the end

echo -e "${RED}########################################################################${NC}"
echo "Enumerating "$((($NUM * 4) * 10))" hosts..." # Math is done to show the actual amount of hosts Nmap enumerates
echo "Looking for open port 22..."

while [ $ITR -le $NUM ]; do # Main loop; It seems that more then 4 processes of Nmap at a time seem to throw RTTVAR errors all over the place
        echo ""                                 # I have not tested this theory on any other computer so results may vary
        echo -e "#------------------${PURPLE}$PERC% complete${NC}------------------#" # Prints the percentage of progress
         nmap -sS -p 22 -Pn -n -T5 --max-retries 1 --max-rtt-timeout 500ms -iR $NUM | (grep -B 4 open >> $IPDIR/temp22.txt && echo -e "${RED}#*****#${NC}One or more Open SSH ports detected.${RED}#*****#${NC}") & 
         nmap -sS -p 22 -Pn -n -T5 --max-retries 1 --max-rtt-timeout 500ms -iR $NUM | (grep -B 4 open >> $IPDIR/temp22.txt && echo -e "${RED}#*****#${NC}One or more Open SSH ports detected.${RED}#*****#${NC}") & 
         nmap -sS -p 22 -Pn -n -T5 --max-retries 1 --max-rtt-timeout 500ms -iR $NUM | (grep -B 4 open >> $IPDIR/temp22.txt && echo -e "${RED}#*****#${NC}One or more Open SSH ports detected.${RED}#*****#${NC}") & 
         nmap -sS -p 22 -Pn -n -T5 --max-retries 1 --max-rtt-timeout 500ms -iR $NUM | (grep -B 4 open >> $IPDIR/temp22.txt && echo -e "${RED}#*****#${NC}One or more Open SSH ports detected.${RED}#*****#${NC}") & 
        wait                                                                        # ^^^^^ The code above gets executed only if there is something to grep which allows me to be able
        PERC=$((PERC + 10))                                                         # ^^^^^ to tell when one or more hosts with an open port 22 have been detected
        ITR=$((ITR + ADDITR))
done
        echo ""
        echo -e "#------------------${PURPLE}$PERC% complete${NC}------------------#" # Prints the final 100% of progress because the iteration is from 0%-90% with only 10 iterations (which can be changed)
grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" $IPDIR/temp22.txt >> $IPDIR/$FILE # This greps out only the IP addresses so that none of the other output from Nmap is in the host list

WC=`wc -l $FILE | grep -o -E '[0-9]{1,4}'` # Count of IPs at the end to subtract from the count of IPs at the beginning
echo ""
echo $(($WC - $START)) "new addresses have been added" # Math done for knowing how many IPs were added
echo "For a total of $WC addresses in file $FILE"
echo ""
rm $IPDIR/temp22.txt # Remove the temp file so that you don't get duplicate IPs in the host list
echo "Complete... Thank you for using Saloaty's SSH Scanner --==> Now Exiting"
echo -e "${RED}########################################################################${NC}"

# This regex below is appearently supposed to validate IP addresses as well;
# But I have not validated that yet so I use the more basic one above
#"(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
